export enum Icons {
  CART_ICON = require('./cart.png'),
  DEBUG_ICON = require('./debug.png'),
  FAVORITE_ICON = require('./favorite.png'),
  FB_ICON = require('./fb.png'),
  HOME_ICON = require('./home.png'),
  INSTA_ICON = require('./insta.png'),
  LOGOUT_ICON = require('./logout-icon.png'),
  MENU_ICON = require('./menu.png'),
  MENU_ACTIVE_ICON = require('./menu_active.png'),
  MENU_INACTIVE_ICON = require('./menu_inactive.png'),
  NOTIFICATION_ICON = require('./notification.png'),
  OFFERS_ICON = require('./offers.png'),
  OFFERS_ACTIVE_ICON = require('./offers_active.png'),
  ORDER_HISTORY_ICON = require('./order-history.png'),
  REWARDS_ICON = require('./rewards.png'),
  RIDER_ICON = require('./rider.png'),
  RIDER_ACTIVE_ICON = require('./rider_active.png'),
  STORE_ICON = require('./store.png'),
  STORE_ACTIVE_ICON = require('./store_active.png'),
  USER_ICON = require('./user.png'),
  YOUTUBE_ICON = require('./youtube.png'),
}
