import {
  APP_MODE,
  APP_API_URL,
  PLAY_STORE_URL,
  APP_STORE_URL,
  APP_SECRET_KEY,
  GOOGLE_MAPS_API_KEY
} from '@env';

export const AppConfig = {
  APP_MODE,
  APP_API_URL,
  PLAY_STORE_URL,
  APP_STORE_URL,
  APP_SECRET_KEY,
  GOOGLE_MAPS_API_KEY
};
