export enum StorageKeys {
  APP_THEME = 'APP_THEME',
  APP_LANGUAGE = 'APP_LANGUAGE',
  FIRST_LAUNCH = 'FIRST_LAUNCH',
  PROFILE_DATA = 'PROFILE_DATA',
  CART = 'CART',
  SERVICE_METHOD = 'SERVICE_METHOD',
  TOKEN = 'TOKEN',
}

export type STORAGES_KEY = StorageKeys;
