export enum Screens {
  MAIN = 'MAIN',
  TRACKER = 'TRACKER',
  STORES = 'STORES',
  CART = 'CART',
  OFFERS = 'OFFERS',
  PROFILE = 'PROFILE',
  ORDER_HISTORY = 'ORDER_HISTORY',
  FAVORITES = 'FAVORITES',
  REWARDS = 'REWARDS',
  NOTIFICATIONS = 'NOTIFICATIONS',
  ORDER_CONFIRMATION = 'ORDER_CONFIRMATION',
  TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  LOGIN = 'LOGIN',
}


