export enum Screens {
  TRACKER = 'TRACKER',
  STORES = 'STORES',
  MAIN = 'MAIN',
  OFFERS = 'OFFERS',

  PROFILE = 'PROFILE',
  ORDER_HISTORY = 'ORDER_HISTORY',
  ORDER_DETAILS = 'ORDER_DETAILS',
  FAVORITES = 'FAVORITES',
  REWARDS = 'REWARDS',
  NOTIFICATIONS = 'NOTIFICATIONS',

  CART = 'CART',
  ORDER_CONFIRMATION = 'ORDER_CONFIRMATION',

  LOGIN = 'LOGIN',
  SIGN_UP = 'SIGN_UP',
  OTP_VERIFY = 'OTP_VERIFY',
  TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
}


